name: Update Gallery
on:
  push:
    paths-ignore:
      - 'index.html'
jobs:
  update_gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Update gallery
        run: |
          echo "Updating gallery..."
          # build up the gallery content in a variable
          gallery=""
          for filename in images/*; do
            file_name_only=$(basename "$filename" | sed 's/\.[^.]*$//')
            gallery+="<div class=\"carousel\"><h2>$file_name_only</h2><img src=\"$filename\" alt=\"Artwork\"></div>"
          done
          # read the html template file content into a variable
          template=$(cat template.html)
          # replace the placeholder in the template with the gallery content
          html=${template//PLACEHOLDER/$gallery}
          # write the result to the index.html file
          echo "$html" > index.html
      - name: Commit and push if it changed 
        run: |
          git diff
          git config --global user.email "19993683+Jaxsbr@users.noreply.github.com"
          git config --global user.name "Jaxsbr"
          git commit -am "Update gallery" || exit 0 
          git push
